apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2
  namespace: argocd
  labels:
    {{- toYaml .Values.cluster2.labels | nindent 4 }}  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.cluster2.source.repoURL }}
    targetRevision: {{ .Values.cluster2.source.targetRevision }}
    path: {{ .Values.cluster2.source.path }}  
    directory:
      recurse: true
      include: '*.yaml'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true