---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-helm-arm-1-29-blueprint
spec:
  credentials:
    source: Secret
    secretRef:
      name: arm-1-29-connection
      namespace: upbound-system
      key: kubeconfig
