apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: test-namespace-arm-1-29-blueprint
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          name: "test-namespace-arm-1-29-blueprint"
  providerConfigRef:
    name: provider-config-k8s-arm-1-29-blueprint