---
{{/* Kustomization to be applied on management cluster*/}}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ printf "%s-%s-%s" .Values.sellerName .Values.addonName .Values.addonVersion | lower | trunc 63 }}
  namespace: {{ .Values.upboundNamespace }}
  labels:
    app: aws-sleek-addon
    seller: {{ .Values.sellerName}}
    addon: {{ .Values.addonName}}
    addon-version: {{ .Values.addonVersion }}
spec:
  interval: 30s
  path: ./addons/{{ .Values.sellerName}}/{{ .Values.addonName}}/{{ .Values.addonVersion }}/manifests/management-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .Values.gitRepository | default (printf "gr-%s-%s-%s" .Values.sellerName .Values.addonName .Values.addonVersion) | lower | trunc 63 }}
