---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: addon-eks-pod-identity-agent-arm-1-29
spec:
  forProvider:
    addonName: eks-pod-identity-agent
    region: us-east-1
    clusterName: arm-1-29-blueprint
  providerConfigRef:
    name: provider-config-aws-arm-1-29-blueprint
