---
apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: cluster-auth-k8s-amd-1-29-blueprint
spec:
  forProvider:
    region: us-east-1
    clusterName: amd-1-29-blueprint
  providerConfigRef:
    name: provider-config-aws-amd-1-29-blueprint
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: kubecontext-amd-1-29
