---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-helm-amd-1-29-blueprint
spec:
  credentials:
    source: Secret
    secretRef:
      name: kubecontext-amd-1-29
      namespace: upbound-system
      key: kubeconfig
