addonNamespace: ex-sol
sellerName: example-software
addonName: solution
addonVersion: 1.0.0
architectures:
  - arm64
  - amd64
kubernetesVersion:
  - 1.26
  - 1.27
  - 1.28
secretMapping:
  exampleSecret:
    - secretKeyOne
    - secretKeyTwo
