---
# Source: aws-sleek-addon-installation-kustomization/templates/addon.yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: eks-pod-identity-agent-arm-1-29
spec:
  forProvider:
    addonName: eks-pod-identity-agent
    region: us-east-1
    clusterName: arm-1-29-blueprint
  providerConfigRef:
    name: irsa-management-cluster
---
# Source: aws-sleek-addon-installation-kustomization/templates/addon.yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: eks-pod-identity-agent-amd-1-29
spec:
  forProvider:
    addonName: eks-pod-identity-agent
    region: us-east-1
    clusterName: amd-1-29-blueprint
  providerConfigRef:
    name: irsa-management-cluster
