repoUrl: https://github.com/jalawala/aws-eks-addon-publication-main 

upboundNamespace: upbound-system
providerConfigName: irsa-providerconfig

testingMarketplaceSellerAlias: cloudsoft-development

region: us-east-1

# This map uses as *key* the name of the architecture and the kubernetes version as is expected in the issue input.
# The *value* is the name of the cluster that matches those constrains
archK8sVersionClusterNameMap:
  amd64-1.26: amd-1-26-blueprint
  amd64-1.29: amd-1-29-blueprint
  amd64-1.28: amd-1-28-blueprint
  arm64-1.26: arm-1-26-blueprint
  arm64-1.27: arm-1-29-blueprint
  arm64-1.28: arm-1-28-blueprint
