---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-k8s-amd-1-29-blueprint
spec:
  credentials:
    source: Secret
    secretRef:
      name: amd-1-29-connection
      namespace: upbound-system
      key: kubeconfig
