---
# Source: addon-management-cluster-manifests/templates/management-cluster-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management-cluster-addon-installation
  namespace: upbound-system
  labels:
    cluster: management-cluster
spec:
  interval: 30s
  path: ./approved-addons/management-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: addon-publication
