apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ns-created-with-cp # Namespace name
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          example: "true"
  providerConfigRef:
    name: provider-config-k8s-amd-1-29-blueprint