cluster1:
  labels:
    cluster: amd-1-29-blueprint
  source:
    repoURL: https://github.com/jalawala/aws-eks-addon-publication-main
    targetRevision: main
    path: ./clusters/cluster1/infra
cluster2:
  labels:
    cluster: arm-1-29-blueprint
spec:
  destination:
    server: https://kubernetes.default.svc
