cluster1:
  labels:
    cluster: amd-1-29-blueprint
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-workloads
    targetRevision: main
    path: clusters/cluster1/infra
cluster2:
  labels:
    cluster: arm-1-29-blueprint
spec:
  destination:
    server: https://kubernetes.default.svc
