apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ .Values.gitAddonsRepositoryName}}
  namespace:  {{ .Values.upboundNamespace }}
spec:
  interval: 5m0s
  url: {{ .Values.repoUrl }}
  ref:
    branch: {{ .Values.gitAddonsRepositoryBranch }}
  secretRef:
    name: github-token
