---
# Source: aws-sleek-addon/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: example-ns
  name: example-ns
---
## Source: aws-sleek-addon/templates/addon.yaml
#apiVersion: eks.aws.upbound.io/v1beta1
#kind: Addon
#metadata:
#  name: example-addon-addon-tester-amd-1-28
#  namespace: example-ns
#spec:
#  forProvider:
#    addonName: example-addon
#    region: eu-north-1
#    clusterName: addon-tester-amd-1-28
#  providerConfigRef:
#    name: default
#---
## Source: aws-sleek-addon/templates/addon.yaml
#apiVersion: eks.aws.upbound.io/v1beta1
#kind: Addon
#metadata:
#  name: example-addon-addon-tester-arm-1-28
#  namespace: example-ns
#spec:
#  forProvider:
#    addonName: example-addon
#    region: eu-north-1
#    clusterName: addon-tester-arm-1-28
#  providerConfigRef:
#    name: default
---
# Source: aws-sleek-addon/templates/externalSecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amp-external-secret-examplesecretone
  namespace: example-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: examplesecretone
    creationPolicy: Owner
  data:
    - secretKey: secretKeyOneOne
      remoteRef:
        key: example-seller/example-addon/1.0.0
        property: secretKeyOneOne
        decodingStrategy: Base64
    - secretKey: secretKeyOneTwo
      remoteRef:
        key: example-seller/example-addon/1.0.0
        property: secretKeyOneTwo
        decodingStrategy: Base64
---
# Source: aws-sleek-addon/templates/externalSecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amp-external-secret-examplesecrettwo
  namespace: example-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: examplesecrettwo
    creationPolicy: Owner
  data:
    - secretKey: secretKeyTwoOne
      remoteRef:
        key: example-seller/example-addon/1.0.0
        property: secretKeyTwoOne
        decodingStrategy: Base64
    - secretKey: secretKeyTwoTwo
      remoteRef:
        key: example-seller/example-addon/1.0.0
        property: secretKeyTwoTwo
        decodingStrategy: Base64
