{{ if .Values.secretMapping }}
  {{- range $secret, $secretKeys := .Values.secretMapping }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amp-external-secret-{{ lower $secret }}
  namespace: {{ $.Values.addonNamespace}}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ lower $secret }}
    creationPolicy: Owner
  data:
    {{- range $secretKey := $secretKeys }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.sellerName }}/{{ $.Values.addonName }}/{{ $.Values.addonVersion }}
        property: {{ $secretKey }}
        decodingStrategy: Base64
    {{- end }}{{/*  # secretKey loop */}}
  {{end}} {{/* secretMapping loop */}}
{{end}} {{/*  if */}}
